import React from 'react'

export default function Recipe() {
  return (
    <div>
        <div>RECIPE COMPONENT FOR RECIPE THAT IS GENERATED</div>
        <div>WILL NEED TO IMPORT AND ACCESS RECIPE DATA</div>
        <div>NEED TO HAVE THE CONTROLLER FUNCTION THAT CREATES THE RECIPE ALSO SET THE RECIPE ID</div>
        <div>BUTTON THAT ACTS AS A SUBMISSION WILL NEED TO BE A STATE THAT IS PASSED DOWN TO PANTRY FORM AND RECIPE</div>

    </div>
  )
}
